name: qgpm_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.8.0
  - torchvision=0.23.0
  - numpy=1.20.1
  - pillow=11.3.0
  - pyyaml=5.4.1
  - requests=2.32.3
  - tqdm=4.67.1
  - pip
  - pip:
    - timm==1.0.19
    - kaggle==1.7.4.5
    - huggingface-hub==0.34.4
    - safetensors==0.6.2
    - python-slugify==8.0.4
    - text-unidecode==1.3
    - bleach==6.2.0
    - jinja2==3.1.6
    - markupSafe==3.0.2
    - packaging==20.9
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - six==1.15.0
    - typing_extensions==4.14.1
    - urllib3==2.4.0
    - webencodings==0.5.1
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - idna==3.10
    - filelock==3.19.1
    - fsspec==2025.7.0
    - hf-xet==1.1.8
    - mpmath==1.3.0
    - networkx==3.2.1
    - sympy==1.14.0
